NAME = minishell
CC = cc
FLAGS = -Werror -Wextra -Wall

LIBFT_PATH = libft
LIBFT = $(LIBFT_PATH)/libft.a

SRCS = src/main.c \
	src/executor/test_executor.c \
	src/executor/path_utils.c\
		src/parser/checker.c\
		src/parser/lexer.c\
		src/parser/handler_args.c\
		src/utils/utils.c\
		src/utils/utils_2.c\
		src/init_mini/mini_init.c\
		src/builtins/built.c\
		src/builtins/builtin_exit.c\
		src/utils/cmd_utils.c\
		src/builtins/builtin_env.c\

OBJS = $(SRCS:.c=.o)

################################################################################
##                                    COLORS                                 ##
################################################################################

END=\033[0m
BOLD=\033[1m
GREEN=\033[0;32m
RED=\033[0;31m
BLUE=\033[0;34m
YELLOW=\033[33m
MAGENTA=\033[35m
TURQUOISE=\033[36m

################################################################################
##                                     RULES                                  ##
################################################################################

all: $(NAME)

head:
	@echo "$(RED)"
	@echo "MWWMNWWNMNWWNMWWMNWWNMXdOXMWNMNWWNMNWMNMWNMNWWNMWWMNWWNKdXWNMWWMNWWNMNWMNMWNMNWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWxldXWWWWWN0ONWWWWWWWWWWWWWWN0ONWWWWWNxldNWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWX'cNWWWWWWolKWWWWWWWWWWWWWWWWWWXocNWWWWWWd.KWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWW..WWWWWWWclWWWWWWWWWWWWWWWWWWWWWWx,WWWWWWW;.NWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWO cWWWWWWl NWWWWWWWWWWWWWWWWWWWWWWW.;WWWWWWx dWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWW: oWWWWWk .doxxWWWWWNWWWWNWWWWWOdod' oWWWWWO .WWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWW. lWWWWWNkkkdo,.cOXl0WWWWKl00l.'ldkkOXWWWWWx  XWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWX  .kxl:,.  .',cl;   , ,, ,   ,lc;'.  .,:ldx;  kWWWWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWWWWWo, .;lxKXNNNXOxo;            ,lxOXXNNXKko:. 'oXWWWWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWWWWWWWNWWWKd,...,;lll.          .loc:,.. 'o0WWWNWWWWWWWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWWWWWWWXx;. .cONWWNkc..:        :'.:kXWWNOl' .;dKWWWWWWWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWWWNkc.  'dXWWWX;. .lKWo        cWXo. .,0WWWNd,  .:xNWWWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWWl   .oXWWWWWW'  kWWWc          'WWWO. .NWWWWWNd'   :NWWWWWWWWWWWW" && sleep 0.07
	@echo "WWWWWWWWWWWWWk.  .NWWWWWWWWd  XWWWc          'WWWW. :WWWWWWWWN'  .dWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWO;  :kNWWWWWW. 'NWWN          0WWW:  NWWWWWNOc. ,xNWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWXc   .0WWWWK  .KWWl        ,WWN'  xWWWWN.   ;KWWWWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWWWK.  :WWWWW:  kWWN.       KWWK  'WWWWWo   OWWWWWWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWWWWK   WWWWWX  cWWWk      oWWWx  0WWWWW.  OWWWWWWWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWWWWWd  xWWWWWl .WWWW:    .WWWW; ;WWWWWK  :WWWWWWWWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWWWWWN. ;WWWWWN  XWWWNlWWdKWWWW  KWWWWWo  XWWWWWWWWWWWWWWWWWWWW" && sleep 0.06
	@echo "WWWWWWWWWWWWWWWWWWWWWWo .WWWWWW: dWWWWWWWWWWWW0 'WWWWWW, ;WWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWN  XWWWWWk ;WWWWWWWWWWWWo oWWWWWW  OWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWW' OWWWWWN .WWWWWWWWWWWW, OWWWWWX .WWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWo dWWWWWW. WWWWWWWWWWWW. NWWWWWO ;WWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWW0 lWWWWWW, KWWWWWWWWWWW .WWWWWWx xWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWW :WWWWWW: kWWWWWWWWWWX 'WWWWWWo KWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWW.,WWWWWWo xWWWWWWWWWWK ;WWWWWWl WWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWW:,WWWWWWx dWWWWWWWWWWO lWWWWWWc.WWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWo'WWWWWWO oWWWWWWWWWWk oWWWWWW:;WWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWx'WWWWWWK lWWWWWWWWWWx xWWWWWW:lWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWW0'WWWWWWX cWWWWWWWWWWx OWWWWWW:dWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWX'WWWWWWW cWWWWWWWWWWx 0WWWWWW:kWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWW'WWWWWWW cWWWWWWWWWWx XWWWWWWc0WWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWW;WWWWWWW.cWWWWWWWWWWd NWWWWWWlKWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWW:WWWWWWW.cWWWWWWWWWWd WWWWWWWlXWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWlWWWWWWW.cWWWWWWWWWWx WWWWWWWoNWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWdWWWWWWW'cWWWWWWWWWWx WWWWWWWxNWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWkWWWWWWW,lWWWWWWWWWWx.WWWWWWWOWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWW,lWWWWWWWWWWk.WWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW;lWWWWWWWWWWk.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:oWWWWWWWWWWO.WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:dWWWWWWWWWWO'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWcdWWWWWWWWWW0,WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWlxWWWWWWWWWW0,WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWlkWWWWWWWWWWX;WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWoOWWWWWWWWWWX;WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo0WWWWWWWWWWN:WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd0WWWWWWWWWWW:WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWdKWWWWWWWWWWWlWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxXWWWWWWWWWWWoWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWxWWWWWWWWWWWWdWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWkWWWWWWWWWWWWkWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOWWWWWWWWWWWW0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKWWWWWWWWWWWWKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXWWWWWWWWWWWWXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.05
	@echo "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW" && sleep 0.1
	@echo ""
	@sleep 0.3
	@printf "\t$(BOLD)        🕷️  " && sleep 0.1
	@printf "A" && sleep 0.05
	@printf "M" && sleep 0.05
	@printf "A" && sleep 0.05
	@printf "Z" && sleep 0.05
	@printf "I" && sleep 0.05
	@printf "N" && sleep 0.05
	@printf "G" && sleep 0.05
	@printf "-" && sleep 0.05
	@printf "S" && sleep 0.05
	@printf "P" && sleep 0.05
	@printf "I" && sleep 0.05
	@printf "D" && sleep 0.05
	@printf "E" && sleep 0.05
	@printf "R" && sleep 0.05
	@printf "S" && sleep 0.05
	@printf "H" && sleep 0.05
	@printf "E" && sleep 0.05
	@printf "L" && sleep 0.05
	@printf "L" && sleep 0.05
	@printf "  🕷️$(END)\n"
	@sleep 0.3
	@echo "\t        42MLG: by miguel-f & lruiz-to"
	@sleep 0.2
	@echo "\t        Proyecto: $(TURQUOISE)Minishell $(RED)"
	@sleep 0.2
	@echo "\t        Commands:$(TURQUOISE) all clean fclean re $(BLUE)"
	@sleep 0.2
	@echo "\t        🛠 Compiler: $(CC) $(END)\n"
	@sleep 0.3

$(LIBFT):
	$(MAKE) -C $(LIBFT_PATH)

$(NAME): $(OBJS) $(LIBFT)
	$(CC) $(FLAGS) -o $(NAME) $(OBJS) $(LIBFT) -lreadline

clean:
	rm -f $(OBJS)
	$(MAKE) -C $(LIBFT_PATH) clean

fclean: clean
	rm -f $(NAME)
	$(MAKE) -C $(LIBFT_PATH) fclean

re: fclean all

.PHONY: all clean fclean re head